spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://nicolasparrado123_db_user:Nicolindo1*@cluster0.q7wt1aw.mongodb.net/dosw_library}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:dosw_library}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
