spring.application.name=DOSW-Library
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=dosw1234
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=dosw-library

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.profiles.active=relational
